/**
 * Hand-maintained stub. This file is NOT auto-generated by the Convex CLI.
 * If you rename the `cleanup` internal mutation in rateLimits.ts, update
 * the path string here too, otherwise the daily cron will silently break.
 */
import { makeFunctionReference } from "convex/server";

export const internal = {
  rateLimits: {
    cleanup: makeFunctionReference<"mutation", Record<string, never>>("rateLimits:cleanup"),
  },
};
